'use client';
/* eslint-disable @next/next/no-img-element -- Supabase media URLs are operator-supplied and already transformed upstream. */

import { useState } from 'react';
import { setProductMedia } from '@/app/admin/commerce/products/actions';

type Asset={id:string;label:string;url:string|null;alt:string|null};
export function ProductMediaManager({productId,assets,initialIds}:{productId:string;assets:Asset[];initialIds:string[]}){
  const [ids,setIds]=useState(initialIds);
  const selected=ids.map(id=>assets.find(asset=>asset.id===id)).filter((x):x is Asset=>Boolean(x));
  const available=assets.filter(asset=>!ids.includes(asset.id));
  const move=(index:number,delta:number)=>setIds(current=>{const next=[...current];const target=index+delta;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target]!,next[index]!];return next});
  return <section className="rounded-card-lg border border-cherie-lace bg-white/55 p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-2xl">Ürün medyası</h2><p className="mt-1 text-sm text-cherie-soft-ink">İlk görsel kapaktır. Sıralamayı değiştirin; arşivlenmiş dosyalar seçilemez.</p></div><a href="/admin/media" className="text-sm font-bold text-cherie-burgundy hover:underline">Medya yükle →</a></div><div className="mt-5 grid gap-3">{selected.map((asset,index)=><div key={asset.id} className="flex items-center gap-3 rounded-control border border-cherie-lace p-3"><div className="size-12 overflow-hidden rounded-control bg-cherie-ivory">{asset.url&&<img src={asset.url} alt="" className="size-full object-cover"/>}</div><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{index===0?'Kapak · ':''}{asset.label}</strong><span className="block truncate text-xs text-cherie-soft-ink">{asset.alt||'Alt metin eksik'}</span></div><button type="button" aria-label="Yukarı taşı" onClick={()=>move(index,-1)} disabled={index===0} className="cherie-button-secondary px-3">↑</button><button type="button" aria-label="Aşağı taşı" onClick={()=>move(index,1)} disabled={index===selected.length-1} className="cherie-button-secondary px-3">↓</button><button type="button" onClick={()=>setIds(current=>current.filter(id=>id!==asset.id))} className="text-sm font-bold text-cherie-error">Kaldır</button></div>)}{selected.length===0&&<p className="rounded-control border border-dashed border-cherie-lace p-5 text-sm text-cherie-soft-ink">Henüz medya atanmadı. Yayın için en az bir dosya gerekir.</p>}</div><div className="mt-5 flex flex-wrap gap-3"><select aria-label="Medya seç" defaultValue="" onChange={event=>{if(event.target.value)setIds(current=>[...current,event.target.value]);event.target.value=''}} className="cherie-field max-w-sm"><option value="">Kütüphaneden ekle…</option>{available.map(asset=><option key={asset.id} value={asset.id}>{asset.label}</option>)}</select><form action={setProductMedia}><input type="hidden" name="id" value={productId}/><input type="hidden" name="media_ids" value={ids.join(',')}/><button className="cherie-button-primary">Medya sırasını kaydet</button></form></div></section>;
}
