import type { Database } from '@/lib/supabase/database.types';
import { changeProductLifecycle, saveProduct } from '@/app/admin/commerce/products/actions';

type Product = Database['public']['Tables']['products']['Row'];
type Option = { id: string; label: string };
export function ProductForm({ product, categories, collections, canPublish, error }: { product?: Product; categories: Option[]; collections: Option[]; canPublish: boolean; error?: string }) {
  return <form action={saveProduct} className="grid gap-6 xl:grid-cols-[1.618fr_1fr]">
    {product && <input type="hidden" name="id" value={product.id}/>}<div className="space-y-6">
      {error && <div role="alert" className="rounded-control border border-cherie-error/30 bg-cherie-error/10 p-4 text-sm text-cherie-error">{error}</div>}
      <Fieldset title="Temel bilgiler" description="Müşterinin ürün sayfasında göreceği çekirdek içerik."><Field label="Ürün adı" name="name" required defaultValue={product?.name}/><Field label="Slug" name="slug" required defaultValue={product?.slug} hint="Örnek: inci-muhur-davetiye"/><label className="grid gap-2 text-sm font-semibold">Açıklama<textarea name="description" defaultValue={product?.description ?? ''} rows={8} maxLength={6000} className="cherie-field resize-y"/><span className="text-xs font-normal text-cherie-soft-ink">Yayın öncesinde zorunludur. En az 20 karakterlik açık bir açıklama yazın.</span></label><div className="grid gap-4 sm:grid-cols-2"><Select label="Kategori" name="category_id" options={categories} value={product?.category_id}/><Select label="Koleksiyon" name="collection_id" options={collections} value={product?.collection_id}/></div></Fieldset>
      <Fieldset title="Ticaret davranışı" description="Fiyat ve sipariş davranışı sunucuda tekrar doğrulanır."><div className="grid gap-4 sm:grid-cols-2"><Select label="Davranış" name="behavior_type" value={product?.behavior_type ?? 'inquiry_only'} options={[{id:'cart_enabled',label:'Doğrudan satış'},{id:'proof_required_cart',label:'Prova onaylı satış'},{id:'digital_checkout',label:'Dijital satış'},{id:'quote_required',label:'Teklif gerekli'},{id:'inquiry_only',label:'Bilgi talebi'},{id:'reservation_request',label:'Rezervasyon talebi'},{id:'city_dependent_service',label:'Şehre bağlı hizmet'}]}/><Field label="Baz fiyat (TRY)" name="base_price" type="number" step="0.01" min="0" defaultValue={product?.base_price ?? ''}/><Select label="Stok modeli" name="stock_mode" value={product?.stock_mode ?? 'made_to_order'} options={[{id:'in_stock',label:'Stokta'},{id:'made_to_order',label:'Siparişe özel üretim'},{id:'preorder',label:'Ön sipariş'},{id:'unavailable',label:'Mevcut değil'}]}/><Field label="Üretim süresi (gün)" name="production_time_days" type="number" min="0" max="365" defaultValue={product?.production_time_days ?? ''}/></div><div className="grid gap-3 sm:grid-cols-2"><Check name="proof_required" label="Prova onayı gerekli" checked={product?.proof_required}/><Check name="is_personalizable" label="Kişiselleştirilebilir" checked={product?.is_personalizable}/></div></Fieldset>
    </div>
    <aside className="space-y-5 xl:sticky xl:top-28 xl:self-start"><div className="rounded-card-lg border border-cherie-lace bg-cherie-paper/60 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-cherie-brass">Kayıt durumu</p><p className="mt-3 text-sm"><strong>{product?.archived_at?'Arşivlendi':product?.status==='published'?'Yayında':'Taslak'}</strong></p><button type="submit" className="mt-5 min-h-12 w-full rounded-control bg-cherie-burgundy px-4 text-sm font-bold text-white hover:bg-cherie-cherry">{product ? 'Değişiklikleri kaydet' : 'Taslağı oluştur'}</button></div><div className="rounded-card-lg border border-cherie-lace p-5"><h2 className="font-display text-2xl">Yayın kontrolü</h2><ul className="mt-3 space-y-2 text-sm text-cherie-soft-ink"><li>• Benzersiz ve okunabilir slug</li><li>• En az 20 karakter açıklama</li><li>• Satış ürünlerinde geçerli fiyat</li><li>• En az bir aktif medya</li><li>• Yayın işlemi sunucuda atomik doğrulanır</li></ul>{product&&<div className="mt-4 grid gap-2">{product.archived_at?<button formAction={changeProductLifecycle.bind(null, 'restore')} className="cherie-button-secondary">Arşivden çıkar</button>:<>{canPublish&&product.status!=='published'&&<button formAction={changeProductLifecycle.bind(null, 'publish')} className="cherie-button-primary">Hazırlığı doğrula ve yayınla</button>}<button formAction={changeProductLifecycle.bind(null, 'archive')} className="cherie-button-secondary text-cherie-error">Ürünü arşivle</button></>}</div>}</div></aside>
  </form>;
}
function Fieldset({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <fieldset className="space-y-5 rounded-card-lg border border-cherie-lace bg-white/55 p-5 md:p-7"><legend className="px-1 font-display text-2xl">{title}</legend><p className="text-sm text-cherie-soft-ink">{description}</p>{children}</fieldset>; }
function Field({ label, name, hint, ...props }: { label: string; name: string; hint?: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="grid gap-2 text-sm font-semibold">{label}<input name={name} className="cherie-field" {...props}/>{hint && <span className="text-xs font-normal text-cherie-soft-ink">{hint}</span>}</label>; }
function Select({ label, name, options, value }: { label: string; name: string; options: Option[]; value?: string | null }) { return <label className="grid gap-2 text-sm font-semibold">{label}<select name={name} defaultValue={value ?? ''} className="cherie-field"><option value="">Seçilmedi</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>; }
function Check({ name, label, checked }: { name: string; label: string; checked?: boolean }) { return <label className="flex min-h-12 items-center gap-3 rounded-control border border-cherie-lace px-4 text-sm font-semibold"><input type="checkbox" name={name} defaultChecked={checked} className="cherie-check size-4"/>{label}</label>; }
