import Link from 'next/link';
import { Inbox, Plus, Search } from 'lucide-react';

export type ResourceColumn<Row> = { label: string; value: (row: Row) => React.ReactNode; mobile?: boolean };

export function ResourceList<Row extends { id: string }>({ eyebrow, title, description, rows, columns, total, createHref, createLabel, query, error }: { eyebrow: string; title: string; description: string; rows: Row[]; columns: ResourceColumn<Row>[]; total: number; createHref?: string; createLabel?: string; query?: string; error?: string }) {
  return <div className="mx-auto max-w-[1680px] space-y-6 p-4 md:p-7 xl:p-9">
    <header className="flex flex-col justify-between gap-4 border-b border-cherie-lace pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cherie-brass">{eyebrow}</p><h1 className="font-display text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-cherie-soft-ink">{description}</p></div>{createHref && <Link href={createHref} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-control bg-cherie-burgundy px-4 text-sm font-bold text-white"><Plus className="size-4"/>{createLabel ?? 'Yeni kayıt'}</Link>}</header>
    {error && <div role="alert" className="rounded-control border border-cherie-error/30 bg-cherie-error/10 p-4 text-sm text-cherie-error">{error}</div>}
    <form className="flex max-w-2xl gap-3"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-control border border-cherie-lace bg-white/60 px-3"><Search className="size-4 text-cherie-soft-ink"/><span className="sr-only">Ara</span><input name="q" defaultValue={query} placeholder={`${title} içinde ara`} className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><button className="rounded-control border border-cherie-burgundy px-4 text-sm font-semibold text-cherie-burgundy">Ara</button></form>
    {!rows.length ? <div className="rounded-card-lg border border-dashed border-cherie-lace py-16 text-center"><Inbox className="mx-auto size-7 text-cherie-brass"/><h2 className="mt-4 font-display text-2xl">Kayıt bulunamadı</h2><p className="mt-2 text-sm text-cherie-soft-ink">Aramayı temizleyin veya ilk kaydı oluşturun.</p></div> : <><div className="grid gap-3 md:hidden">{rows.map((row) => <article key={row.id} className="rounded-card-lg border border-cherie-lace bg-white/60 p-4">{columns.filter((column) => column.mobile !== false).map((column) => <div key={column.label} className="flex min-h-10 items-start justify-between gap-4 border-b border-cherie-lace/60 py-2 last:border-0"><span className="text-xs font-bold uppercase tracking-wider text-cherie-soft-ink">{column.label}</span><div className="text-right text-sm">{column.value(row)}</div></div>)}</article>)}</div><div className="hidden overflow-hidden rounded-card-lg border border-cherie-lace bg-white/60 md:block"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-cherie-paper text-xs uppercase tracking-wider text-cherie-soft-ink"><tr>{columns.map((column) => <th key={column.label} className="px-5 py-4">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-cherie-lace">{rows.map((row) => <tr key={row.id} className="hover:bg-cherie-paper/45">{columns.map((column) => <td key={column.label} className="px-5 py-4">{column.value(row)}</td>)}</tr>)}</tbody></table></div></div></>}
    <p className="text-sm text-cherie-soft-ink">Toplam {total} kayıt · Bu görünüm en güncel 100 kaydı gösterir.</p>
  </div>;
}

export function StateBadge({ value }: { value: string }) { const good=['published','active','approved','passed','delivered','completed','current'].includes(value); const bad=['failed','rejected','cancelled','archived'].includes(value); return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${good?'bg-cherie-success/10 text-cherie-success':bad?'bg-cherie-error/10 text-cherie-error':'bg-cherie-warning/10 text-cherie-warning'}`}>{value}</span>; }
export function AdminDate({ value }: { value?: string | null }) { return <>{value ? new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeZone:'Europe/Istanbul'}).format(new Date(value)) : '—'}</>; }
