create table if not exists public.system_settings(id uuid primary key default gen_random_uuid(),key text not null unique check(key~'^[a-z0-9_.-]+$'),value jsonb not null default'{}',updated_at timestamptz not null default now(),updated_by uuid references public.staff_users(id)on delete set null);
alter table public.system_settings enable row level security;create policy system_settings_staff_read on public.system_settings for select to authenticated using((select public.has_staff_role(array['admin','operations'])));create policy system_settings_admin_write on public.system_settings for all to authenticated using((select public.has_staff_role(array['admin'])))with check((select public.has_staff_role(array['admin'])));grant select,insert,update on public.system_settings to authenticated;

create or replace function public.admin_retry_notification(p_notification_id uuid)
returns void language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_row public.notification_outbox;begin if not(select public.has_staff_role(array['order_operations','commerce_manager','support_agent','admin']))then raise exception'permission denied'using errcode='42501';end if;v_staff:=public.current_staff_id();select*into v_row from public.notification_outbox where id=p_notification_id for update;if v_row.id is null then raise exception'notification not found'using errcode='P0002';end if;if v_row.status not in('retry_scheduled','permanently_failed')then raise exception'notification is not retryable'using errcode='23514';end if;if v_row.sent_at is not null then raise exception'already sent'using errcode='23514';end if;update public.notification_outbox set status='queued',available_at=now(),next_attempt_at=now(),locked_at=null,locked_by=null,failed_at=null,updated_at=now()where id=p_notification_id;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'notification.retry.requested','notification_outbox',p_notification_id,jsonb_build_object('previous_status',v_row.status,'attempts',v_row.attempts,'idempotency_key',v_row.idempotency_key));end$$;

create or replace function public.admin_update_staff(p_staff_id uuid,p_role public.staff_role,p_is_active boolean)
returns void language plpgsql security invoker set search_path=public as $$declare v_actor uuid;v_before jsonb;begin if not(select public.has_staff_role(array['superadmin']))then raise exception'permission denied'using errcode='42501';end if;v_actor:=public.current_staff_id();if v_actor=p_staff_id and not p_is_active then raise exception'cannot deactivate self'using errcode='23514';end if;select jsonb_build_object('role',role,'is_active',is_active)into v_before from public.staff_users where id=p_staff_id for update;if v_before is null then raise exception'staff not found'using errcode='P0002';end if;update public.staff_users set role=p_role,is_active=p_is_active,updated_at=now()where id=p_staff_id;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_actor,'staff.updated','staff_user',p_staff_id,jsonb_build_object('before',v_before,'after',jsonb_build_object('role',p_role,'is_active',p_is_active)));end$$;

revoke all on function public.admin_retry_notification(uuid),public.admin_update_staff(uuid,public.staff_role,boolean)from public, anon, authenticated;grant execute on function public.admin_retry_notification(uuid),public.admin_update_staff(uuid,public.staff_role,boolean)to authenticated;
