create table if not exists public.customer_notes(id uuid primary key default gen_random_uuid(),customer_id uuid not null references public.customers(id)on delete cascade,author_staff_id uuid references public.staff_users(id)on delete set null,note text not null check(length(trim(note))between 1 and 4000),created_at timestamptz not null default now());
create index if not exists customer_notes_customer_created_idx on public.customer_notes(customer_id,created_at desc);alter table public.customer_notes enable row level security;create policy customer_notes_staff on public.customer_notes for all to authenticated using((select public.has_staff_role(array['sales_crm','support_agent','commerce_manager','admin'])))with check((select public.has_staff_role(array['sales_crm','support_agent','commerce_manager','admin'])));grant select,insert on public.customer_notes to authenticated;

create or replace function public.admin_update_lead(p_lead_id uuid,p_status public.lead_status,p_priority text,p_assigned_staff_id uuid,p_next_follow_up_at timestamptz,p_note text,p_lost_reason text)
returns void language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_old public.lead_status;begin if not(select public.has_staff_role(array['sales_crm','commerce_manager','admin']))then raise exception'permission denied'using errcode='42501';end if;if p_priority not in('low','normal','high','urgent')then raise exception'invalid priority'using errcode='23514';end if;if p_status='lost'and length(trim(coalesce(p_lost_reason,'')))<3 then raise exception'lost reason required'using errcode='23514';end if;v_staff:=public.current_staff_id();select status into v_old from public.leads where id=p_lead_id for update;if v_old is null then raise exception'lead not found'using errcode='P0002';end if;update public.leads set status=p_status,priority=p_priority,assigned_staff_id=p_assigned_staff_id,next_follow_up_at=p_next_follow_up_at,lost_reason=case when p_status='lost'then trim(p_lost_reason)else null end,updated_at=now()where id=p_lead_id;if v_old is distinct from p_status then insert into public.lead_status_history(lead_id,from_status,to_status,changed_by)values(p_lead_id,v_old,p_status,v_staff);end if;if nullif(trim(coalesce(p_note,'')),'')is not null then insert into public.lead_notes(lead_id,author_id,note)values(p_lead_id,v_staff,trim(p_note));end if;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'lead.updated','lead',p_lead_id,jsonb_build_object('from',v_old,'to',p_status,'priority',p_priority,'next_follow_up_at',p_next_follow_up_at));end$$;

create or replace function public.admin_convert_lead(p_lead_id uuid,p_target text)
returns uuid language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_lead public.leads;v_customer uuid;v_id uuid;begin if not(select public.has_staff_role(array['sales_crm','commerce_manager','admin']))then raise exception'permission denied'using errcode='42501';end if;if p_target not in('customer','appointment','quote')then raise exception'invalid target'using errcode='22023';end if;v_staff:=public.current_staff_id();select*into v_lead from public.leads where id=p_lead_id for update;if v_lead.id is null then raise exception'lead not found'using errcode='P0002';end if;select id into v_customer from public.customers where(v_lead.email is not null and lower(email)=lower(v_lead.email))or(v_lead.phone is not null and regexp_replace(phone,'\D','','g')=regexp_replace(v_lead.phone,'\D','','g'))limit 1;if p_target='customer'then if v_customer is null then insert into public.customers(name,email,phone,status)values(v_lead.name,v_lead.email,v_lead.phone,'active')returning id into v_customer;end if;update public.leads set status='won',converted_customer_id=v_customer,updated_at=now()where id=p_lead_id;v_id:=v_customer;elsif p_target='appointment'then insert into public.consultations(consultation_number,customer_id,lead_id,assigned_staff_id,note,preferred_slots,status)values('CNS-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISSMS'),v_customer,p_lead_id,v_lead.assigned_staff_id,v_lead.message,jsonb_build_array(v_lead.event_date_or_season),'requested')returning id into v_id;update public.leads set status='appointment',updated_at=now()where id=p_lead_id;else insert into public.quote_requests(customer_id,name,email,phone,event_type,event_date_or_season,city,message,budget_band,status)values(v_customer,v_lead.name,v_lead.email,v_lead.phone,v_lead.event_type,v_lead.event_date_or_season,v_lead.location,v_lead.message,v_lead.budget_band,'proposal_sent')returning id into v_id;update public.leads set status='proposal_sent',updated_at=now()where id=p_lead_id;end if;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'lead.converted','lead',p_lead_id,jsonb_build_object('target',p_target,'result_id',v_id));return v_id;end$$;

revoke all on function public.admin_update_lead(uuid,public.lead_status,text,uuid,timestamptz,text,text),public.admin_convert_lead(uuid,text)from public, anon, authenticated;grant execute on function public.admin_update_lead(uuid,public.lead_status,text,uuid,timestamptz,text,text),public.admin_convert_lead(uuid,text)to authenticated;
