alter table public.orders add column if not exists assigned_staff_id uuid references public.staff_users(id) on delete set null;
create index if not exists orders_assignment_action_idx on public.orders(assigned_staff_id,status,updated_at desc);
alter table public.product_proofs add column if not exists assigned_staff_id uuid references public.staff_users(id) on delete set null,add column if not exists due_at timestamptz;

create or replace function public.admin_update_order_operations(p_order_id uuid,p_assigned_staff_id uuid,p_internal_note text,p_customer_note text)
returns void language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_before jsonb;begin if not(select public.has_staff_role(array['order_operations','commerce_manager','support_agent','admin']))then raise exception'permission denied'using errcode='42501';end if;v_staff:=public.current_staff_id();select jsonb_build_object('assigned_staff_id',assigned_staff_id,'internal_note',internal_note,'customer_note',customer_note)into v_before from public.orders where id=p_order_id for update;if v_before is null then raise exception'order not found'using errcode='P0002';end if;update public.orders set assigned_staff_id=p_assigned_staff_id,internal_note=nullif(trim(p_internal_note),''),customer_note=nullif(trim(p_customer_note),''),updated_at=now()where id=p_order_id;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'order.operations.updated','order',p_order_id,jsonb_build_object('before',v_before,'after',jsonb_build_object('assigned_staff_id',p_assigned_staff_id,'internal_note',p_internal_note,'customer_note',p_customer_note)));end$$;

create or replace function public.admin_complete_quality_check(p_job_id uuid,p_items jsonb,p_note text)
returns uuid language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_check uuid;v_failed int;begin if not(select public.has_staff_role(array['order_operations','commerce_manager','operations','admin']))then raise exception'permission denied'using errcode='42501';end if;if jsonb_typeof(p_items)<>'array'or jsonb_array_length(p_items)=0 then raise exception'quality items required'using errcode='23514';end if;v_staff:=public.current_staff_id();insert into public.quality_checks(production_job_id,status,note,checked_by,checked_at)values(p_job_id,'pending',nullif(trim(p_note),''),v_staff,now())returning id into v_check;insert into public.quality_check_items(quality_check_id,key,label_tr,is_required,passed,note,sort_order)select v_check,x->>'key',x->>'label',coalesce((x->>'required')::boolean,true),(x->>'passed')::boolean,nullif(x->>'note',''),ordinality-1 from jsonb_array_elements(p_items)with ordinality as q(x,ordinality);select count(*)into v_failed from public.quality_check_items where quality_check_id=v_check and is_required and passed is distinct from true;update public.quality_checks set status=case when v_failed=0 then'passed'else'failed'end where id=v_check;update public.production_jobs set status=case when v_failed=0 then'passed'else'rework'end,blocker=case when v_failed=0 then null else'Kalite kontrolü başarısız'end where id=p_job_id;insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'quality.completed','quality_check',v_check,jsonb_build_object('production_job_id',p_job_id,'failed_required',v_failed));return v_check;end$$;

create or replace function public.admin_create_shipment(p_order_id uuid,p_carrier text,p_tracking text,p_package_count int,p_internal_note text)
returns uuid language plpgsql security invoker set search_path=public as $$declare v_staff uuid;v_id uuid;begin if not(select public.has_staff_role(array['order_operations','commerce_manager','operations','admin']))then raise exception'permission denied'using errcode='42501';end if;if length(trim(p_carrier))<2 or length(trim(p_tracking))<3 or p_package_count<1 then raise exception'invalid shipment'using errcode='23514';end if;v_staff:=public.current_staff_id();insert into public.shipments(order_id,carrier_name,tracking_number,package_count,internal_note,status)values(p_order_id,trim(p_carrier),trim(p_tracking),p_package_count,nullif(trim(p_internal_note),''),'preparing')returning id into v_id;insert into public.tracking_events(shipment_id,status,message_tr)values(v_id,'preparing','Gönderi kaydı oluşturuldu');insert into public.audit_log(staff_user_id,action,entity_type,entity_id,diff)values(v_staff,'shipment.created','shipment',v_id,jsonb_build_object('order_id',p_order_id,'package_count',p_package_count));return v_id;end$$;

revoke all on function public.admin_update_order_operations(uuid,uuid,text,text),public.admin_complete_quality_check(uuid,jsonb,text),public.admin_create_shipment(uuid,text,text,int,text)from public, anon, authenticated;
grant execute on function public.admin_update_order_operations(uuid,uuid,text,text),public.admin_complete_quality_check(uuid,jsonb,text),public.admin_create_shipment(uuid,text,text,int,text)to authenticated;
